version: '3.5'

services:
  postgres:
    container_name: db
    image: postgres:14.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres    
    volumes:
      - db-volume:/data/postgres
    ports:
      - "54441:5432"
    networks:
      - rss-network

  rest-rss:
    container_name: rest-rss
    image: rss-test:1.0.0
    volumes:
      - ./appsettings.json:/app/appsettings.json
    ports:
      - "5001:5001"
    networks:
      - rss-network    

networks:
  rss-network:
    driver: bridge 

volumes:
  db-volume:
    external: true    